// <auto-generated />
using System;
using Alumni.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinkAlumni.Migrations
{
    [DbContext(typeof(MVCDemoDbContext))]
    [Migration("20221021190508_add-migration 'InitialMigration'")]
    partial class addmigrationInitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LinkAlumni.Models.Domain.AlumniInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Certificates")
                        .IsRequired()
                        .HasColumnType("nvarchar(8000)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(8000)");

                    b.Property<string>("CompanyAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(8000)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(8000)");

                    b.Property<string>("CurrentJobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(8000)");

                    b.Property<string>("DegreeReceived")
                        .IsRequired()
                        .HasColumnType("nvarchar(8000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(8000)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(8000)");

                    b.Property<int>("GraduationYear")
                        .HasColumnType("int");

                    b.Property<string>("Internships")
                        .IsRequired()
                        .HasColumnType("nvarchar(8000)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(8000)");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("nvarchar(8000)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(8000)");

                    b.Property<long>("PhoneNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("PostGraduateDegree")
                        .IsRequired()
                        .HasColumnType("nvarchar(8000)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(8000)");

                    b.HasKey("Id");

                    b.ToTable("AlumniInformation");
                });
#pragma warning restore 612, 618
        }
    }
}
